setting1:
  setting1_child: saweet
  deep:
    another: my value
    child:
      value: 2

setting2: 5
setting3: <%= 5 * 5 %>
global: 'wat'
name: test

development:
  language: &language_defaults
    haskell:
      paradigm: functional
    smalltalk:
      paradigm: object oriented

  environment: development

language:
  <<: *language_defaults

collides:
  does: not
nested:
  collides:
    does: not either

nil:
'false': false

array:
  -
    name: first
  -
    name: second
